### ISSUE TITLE
Supportare le citazioni all'interno dei blocchi di testo

### ISSUE THREAD

**Issue by olistik** [scuoleparrocchialidesio/www#68]
```css
.rich-text blockquote {
    border-left: 3px solid #ccc;
    padding-left: 1rem;
    margin-left: 0rem;
    font-size: 1.5rem;
    font-style: italic;
    color: #4d4d4d;
}
```
